# Configuratie voor automatische toewijzing van reviewers en assignees
addReviewers: true
addAssignees: true

# Reviewers die automatisch worden toegevoegd aan elke PR
reviewers:
  - scns

# Assignees die automatisch worden toegevoegd aan elke PR en Issue
assignees:
  - scns

# Optionele instellingen
skipKeywords:
  - wip
  - draft
  - "[skip assign]"
  - "discussion"

# Aantal reviewers/assignees dat wordt toegevoegd
numberOfReviewers: 1
numberOfAssignees: 1

# Issue-specifieke instellingen
addAssigneesToIssues: true
skipDraftIssues: true
