# These are supported funding model platforms

github: []
patreon:
open_collective:
ko_fi: maartenschmeitz
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: maartenschmeitz
thanks_dev:
custom: []
bitcoin: 39dDgoRVGTFvFNh6sP1mBR2iSp6jfEnN16
ethereum: 0x67b39d23AD43ae8201653Be83D636c169C06B88f