# Configuration for file-based auto labeling
# See: https://github.com/actions/labeler

# KB Update related files
kb-update:
  - changed-files:
    - any-glob-to-any-file: 
      - "kb-mapping.json"
      - "KB-CACHING-INFO.md"
      - "**/*kb*.json"
      - "**/*knowledge*.md"

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - "*.md"
      - "**/*.md"
      - "docs/**/*"
      - "README*"

# Configuration files
maintenance:
  - changed-files:
    - any-glob-to-any-file:
      - "_config.json"
      - "config.json"
      - "_credentials.json"
      - "credentials.json"
      - "*.json"

# PowerShell scripts
enhancement:
  - changed-files:
    - any-glob-to-any-file:
      - "*.ps1"
      - "*.psm1"
      - "**/*.ps1"

# CI/CD workflows
ci:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/workflows/**/*"
      - ".github/**/*.yml"
      - ".github/**/*.yaml"

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - "package.json"
      - "requirements.txt"
      - "**/package*.json"

# Security related
security:
  - changed-files:
    - any-glob-to-any-file:
      - "SECURITY.md"
      - "**/*security*"

# Breaking changes (if certain files are modified)
breaking-change:
  - changed-files:
    - any-glob-to-any-file:
      - "_credentials.json"
      - "_config.json"
