- name: "major-change"
  color: "d73a4a"
  description: "Major breaking changes"
- name: "breaking-change"
  color: "d73a4a"
  description: "Breaking changes"
- name: "new-feature"
  color: "0075ca"
  description: "New features"
- name: "bugfix"
  color: "d876e3"
  description: "Bug fixes"
- name: "enhancement"
  color: "a2eeef"
  description: "Enhancements"
- name: "refactor"
  color: "a2eeef"
  description: "Code refactoring"
- name: "performance"
  color: "a2eeef"
  description: "Performance improvements"
- name: "maintenance"
  color: "f9d0c4"
  description: "Maintenance tasks"
- name: "ci"
  color: "f9d0c4"
  description: "CI/CD related"
- name: "documentation"
  color: "0052cc"
  description: "Documentation updates"
- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"
- name: "security"
  color: "ee0701"
  description: "Security fixes"
- name: "sync"
  color: "ededed"
  description: "Sync operations"
- name: "minor"
  color: "0075ca"
  description: "Minor changes"
- name: "chore"
  color: "fef2c0"
  description: "Chore tasks"
