name: "Bug report"
description: "Create a bug report to help us improve the myESPhome Project!"
labels: ["bug", "question", "triage:not-checked"]
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Please verify that this bug has NOT been raised before."
      description: "Search in the issues sections by clicking [HERE](https://github.com/scns/Windows-Update-Report-MultiTenant/issues?q=) and read the [Discussions](https://github.com/scns/Windows-Update-Report-MultiTenant/discussions)!"
      options:
        - label: "I checked and didn't find a similar issue"
          required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Describe the bug*"
      description: "A clear and concise description of what the bug is."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "..."
 

  - type: textarea
    id: additional-context
    validations:
      required: true
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Add any other context about the problem here. "